export const GET_CLASS_DATA = 'GET_CLASS_DATA';
export const GET_CLASS_SUCCESS = 'GET_CLASS_SUCCESS';
export const GET_CLASS_ERROR = 'GET_CLASS_ERROR';
export const POST_CLASS_DATA = 'POST_CLASS_DATA';
export const POST_CLASS_SUCCESS = 'POST_CLASS_SUCCESS';
export const POST_CLASS_ERROR = 'POST_CLASS_ERROR';

export const PUT_CLASS_DATA = 'PUT_CLASS_DATA';
export const PUT_CLASS_SUCCESS = 'PUT_CLASS_SUCCESS';
export const PUT_CLASS_ERROR = 'PUT_CLASS_ERROR';
export const DELETE_CLASS_DATA = 'DELETE_CLASS_DATA';
export const DELETE_CLASS_SUCCESS = 'DELETE_CLASS_SUCCESS';
export const DELETE_CLASS_ERROR = 'DELETE_CLASS_ERROR';
